dist: focal
language: ruby
rvm: 2.7.1

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: bundle exec jekyll build

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master

env:
  global:
  - JEKYLL_ENV=production

cache: bundler # caching bundler gem packages will speed up build

deploy:
  provider: firebase
  token:
    secure: "oSfNGehThrCLxofXniNADCpKfvoBVC93+bOhsq6X75z/jAYLhDjhWdbLC+A98vRNS3nubxsz36HFmjkoiahRrjav7I8V8dVgYlIQSfmBked5YtzE9qQIP1otBjFx8KG4tE4tsLR1kcuWrjlq+jIt6hTWkmLiqPUoWl5t+aOOTTOerf38xBFsCA0ixBFR6hGZDLD59TReKFGPxeis1iVnX6iZhRW/LsDE3GMuPs5BL2xSPr/GUZgDYV4swlmo8DzWjQhPm2C5sCRyzh1/kjNzRtCsuy8QYjVjoKmCgwceLdNl5UxUBss6V+qpaLcSHsYm2+AIAGF4p+UKBkacWQh0oShjvHwbeLgZvngFrmkogBL/zxi3OZzbRX3QJ1hUeJx+HsGQ+XS2Io0VOYlLJ/6B5mdwzYxOng8TJlJNAh6wAxIlf8vRkOcAxJ1QnoZDheoRRKf0FwMar39R4k6xHZxhHKmBM2f4SQZaMf0nDcZq4K+fG3zw/Cd1b3M3ZhCB93Z82MYtW6GAeAPukeN8jOA35CIE0Ex1+Xd7XGT/NKi7b3KEt2BbxkDLgbwOxW2SyUVj5GTjJwtWSjWWSmiJh3vkENQWmQlQovlOX1no5fxzvYxq3mhfMUe/vMJp0w0OcI8egCvJVCZwKWSPkGYRsy90vB9W+j/1xeeOISBNJQeYIk8="

notifications:
  email:
    recipients:
    - issei+blog.travisci@issei.org    
    on_success: always
    on_failure: always