dist: focal
language: ruby
rvm: 2.7.1

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script:
- bundle exec jekyll build
- bundle exec htmlproofer ./_site --disable-external --empty-alt-ignore --allow-hash-href

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master

env:
  global:
  - JEKYLL_ENV=production
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

cache: bundler # caching bundler gem packages will speed up build

deploy:
  provider: firebase
  token:
    secure: "oSfNGehThrCLxofXniNADCpKfvoBVC93+bOhsq6X75z/jAYLhDjhWdbLC+A98vRNS3nubxsz36HFmjkoiahRrjav7I8V8dVgYlIQSfmBked5YtzE9qQIP1otBjFx8KG4tE4tsLR1kcuWrjlq+jIt6hTWkmLiqPUoWl5t+aOOTTOerf38xBFsCA0ixBFR6hGZDLD59TReKFGPxeis1iVnX6iZhRW/LsDE3GMuPs5BL2xSPr/GUZgDYV4swlmo8DzWjQhPm2C5sCRyzh1/kjNzRtCsuy8QYjVjoKmCgwceLdNl5UxUBss6V+qpaLcSHsYm2+AIAGF4p+UKBkacWQh0oShjvHwbeLgZvngFrmkogBL/zxi3OZzbRX3QJ1hUeJx+HsGQ+XS2Io0VOYlLJ/6B5mdwzYxOng8TJlJNAh6wAxIlf8vRkOcAxJ1QnoZDheoRRKf0FwMar39R4k6xHZxhHKmBM2f4SQZaMf0nDcZq4K+fG3zw/Cd1b3M3ZhCB93Z82MYtW6GAeAPukeN8jOA35CIE0Ex1+Xd7XGT/NKi7b3KEt2BbxkDLgbwOxW2SyUVj5GTjJwtWSjWWSmiJh3vkENQWmQlQovlOX1no5fxzvYxq3mhfMUe/vMJp0w0OcI8egCvJVCZwKWSPkGYRsy90vB9W+j/1xeeOISBNJQeYIk8="
  skip_cleanup: true

notifications:
  slack:
    on_success: always
    on_failure: always
    secure: "NAKhI4UZ5uf+kjNocMBtvPdPex/tgkfHe18Tm/b9XLyJnJErY1mA6pgO+nG3BrqyuQ5NazyJyLlzc/offhUCC8F+ouKbHx+m7xfR/9o/xY/QhTYpWmEmTgF4rpe4R4aivQMPRmQeXYUoH4TH271zcM5YTFh2cmu6z++lFK56K/8SmukDwDxCU7pGDubXDYadxTUt6jlmnaHdUd4Cukpz7nEcx4QiMU9qAxH9+MFzHJGfqTk5V9wwjetuorqdl3Ib678/EwppSM5FBgHHvkpPItWF+4zinqxOK7bk/7He0C0tXoty1i3uoLlCelr4qsNvEaHWLiCx6ODMdv9VQViwZ2w/GKMMY0gdXC4fWv9qQ9PfdLxYYjitu/4SykRb/htlMlVn3MRReZqVn/UseF0XK/JHxdteAoglTUCDVw7VbLDhzYYG/yPgRGZfZTjlquDWP2FaAl078IhK5jRGHk5yurn2eSe11wwOCNZofEBpzVnXsAvVnGS/+qOWfmst6KvBXfnBNAc+y3fYsYagHxwm4yD+dlmd+AH5kNNwgjeZAOB7kMxWLJVKLRR6X4dRQgtNVpCqpNBR0v2aIbPu1GwEh7CODgoKq3pVN4dSP96GCUWTpiC3v2W5LM2LkIfBnMa/DOH0Q4NJDhptqYwegONww7ybMJEtiiyh6go+BmMqmTw="
  email: false