#! /bin/sh
# vim: sh-mode:sw=4

MASTER_FILE='_tools/hooks/pre-commit'

# Redirect output to stderr
exec 1>&2

# Sanity check
if [ -z "$GIT_DIR" ]; then
    echo "Don't run this script from the command line."
    exit 1
fi

# Update installed hook
if [ -e $MASTER_FILE ]; then
    diff -s $MASTER_FILE "$GIT_DIR/hooks/pre-commit" > /dev/null
    if [ $? -ne 0 ]; then
	cp $MASTER_FILE "$GIT_DIR/hooks/pre-commit"
	echo "Updated pre-commit hook. Please run again."
	exit 1
    fi
else
    echo "$MASTER_FILE not found."
fi

# Run actual pre-commit checks
_tools/check_geotag.py || exit 1
exit 0
